import type { ConfigFieldDefinition } from "../types";
import { defaultFieldValues } from "./defaults";
import { sectionRegistry } from "./sections";

export const fieldRegistry: readonly ConfigFieldDefinition[] = [
  {
    keyPath: "model",
    sectionId: "core-model",
    label: "主模型",
    description: "Codex 默认使用的主模型，通常建议保留为全局设置。",
    defaultBehavior: "未设置时使用 Codex 默认主模型 gpt-5.4。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["gpt-5.4", "gpt-5.4-mini", "gpt-5.4-codex"],
    defaultValue: defaultFieldValues.model,
  },
  {
    keyPath: "service_tier",
    sectionId: "core-model",
    label: "服务档位",
    description: "控制模型调用的服务档位，影响响应速度和成本取向。",
    defaultBehavior: "未设置时按默认 flex 档位运行。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["fast", "flex"],
    defaultValue: defaultFieldValues.service_tier,
  },
  {
    keyPath: "model_reasoning_effort",
    sectionId: "reasoning-output",
    label: "推理强度",
    description: "控制模型在回答前投入的推理程度。",
    defaultBehavior: "未设置时使用 medium 级别的推理强度。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["minimal", "low", "medium", "high", "xhigh"],
    defaultValue: defaultFieldValues.model_reasoning_effort,
  },
  {
    keyPath: "approval_policy",
    sectionId: "security-sandbox",
    label: "审批策略",
    description: "决定何时需要人工确认命令或工具调用。",
    defaultBehavior: "未设置时使用 on-request，在需要时请求审批。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["untrusted", "on-request", "never"],
    risk: "warning",
    defaultValue: defaultFieldValues.approval_policy,
    supportsStructuredValue: true,
    structuredValueDescription:
      "也支持 approval_policy = { granular = { sandbox_approval = true, rules = false, mcp_elicitations = false } } 这类对象形式。",
  },
  {
    keyPath: "sandbox_mode",
    sectionId: "security-sandbox",
    label: "沙箱模式",
    description: "控制文件系统与网络访问的安全边界。",
    defaultBehavior: "未设置时使用 read-only，只允许安全的只读访问。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["read-only", "workspace-write", "danger-full-access"],
    risk: "danger",
    defaultValue: defaultFieldValues.sandbox_mode,
  },
  {
    keyPath: "windows.sandbox",
    sectionId: "security-sandbox",
    label: "Windows 沙箱",
    description: "设置 Windows 原生沙箱模式。",
    defaultBehavior: "未设置时使用 unelevated，保持较低权限运行。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["unelevated", "elevated"],
    risk: "warning",
    defaultValue: defaultFieldValues["windows.sandbox"],
  },
  {
    keyPath: "web_search",
    sectionId: "search-experience",
    label: "Web 搜索",
    description: "控制搜索结果的使用方式与刷新策略。",
    defaultBehavior: "未设置时使用 cached，优先复用缓存索引结果。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["disabled", "cached", "live"],
    defaultValue: defaultFieldValues.web_search,
  },
  {
    keyPath: "project_doc_max_bytes",
    sectionId: "search-experience",
    label: "项目文档上限",
    description: "限制首轮指令中嵌入项目文档的字节数。",
    defaultBehavior: "未设置时使用默认上限 32768 字节。",
    recommendedScope: "global",
    kind: "number",
    defaultValue: defaultFieldValues.project_doc_max_bytes,
  },
  {
    keyPath: "project_doc_fallback_filenames",
    sectionId: "search-experience",
    label: "项目文档兜底文件名",
    description: "当目录缺少 AGENTS.md 时使用的候补文件名列表。",
    defaultBehavior: "未设置时不使用额外候补文件名。",
    recommendedScope: "global",
    kind: "array",
    defaultValue: defaultFieldValues.project_doc_fallback_filenames,
  },
  {
    keyPath: "history.persistence",
    sectionId: "history-notifications",
    label: "历史持久化",
    description: "决定历史记录保存方式。",
    defaultBehavior: "未设置时使用 save-all，保留完整历史。",
    recommendedScope: "project",
    kind: "enum",
    allowedValues: ["save-all", "none"],
    defaultValue: defaultFieldValues["history.persistence"],
  },
  {
    keyPath: "history.max_bytes",
    sectionId: "history-notifications",
    label: "历史上限",
    description: "限制历史文件的最大体积。",
    defaultBehavior: "未设置时沿用 Codex 默认的历史体积上限。",
    recommendedScope: "project",
    kind: "number",
    risk: "warning",
  },
  {
    keyPath: "profile",
    sectionId: "profiles",
    label: "Profile",
    description: "启用的配置预设名称。",
    defaultBehavior: "未设置时不会启用任何命名 profile。",
    recommendedScope: "global",
    kind: "string",
    dynamicOptionsSource: "profiles",
  },
  {
    keyPath: "model_provider",
    sectionId: "model-providers",
    label: "模型提供商",
    description: "默认模型提供商标识，填写的是 [model_providers] 中定义的 provider id。",
    defaultBehavior: "未设置时使用 openai 作为默认提供商。",
    recommendedScope: "global",
    kind: "string",
    defaultValue: defaultFieldValues.model_provider,
    dynamicOptionsSource: "model_providers",
  },
  {
    keyPath: "oss_provider",
    sectionId: "model-providers",
    label: "OSS 提供商",
    description: "--oss 会话使用的默认提供商。",
    defaultBehavior: "未设置时进入 --oss 会话会提示选择 provider。",
    recommendedScope: "global",
    kind: "string",
    dynamicOptionsSource: "model_providers",
  },
  {
    keyPath: "projects",
    sectionId: "project-trust",
    label: "项目可信映射",
    description: "管理全局配置中各项目路径的 trust_level 映射。",
    defaultBehavior: "未设置时不记录显式 trust_level，由 Codex 按默认安全策略处理。",
    recommendedScope: "global",
    kind: "object",
    risk: "warning",
    defaultValue: {},
    structuredValueDescription: "键为项目绝对路径，值对象至少包含 trust_level，取值通常是 trusted 或 untrusted。",
  },
  {
    keyPath: "developer_instructions",
    sectionId: "expert-mode",
    label: "开发者指令",
    description: "注入到 AGENTS.md 之前的额外指令内容。",
    defaultBehavior: "未设置时不会额外注入开发者指令。",
    recommendedScope: "either",
    kind: "string",
    risk: "warning",
  },
  {
    keyPath: "compact_prompt",
    sectionId: "expert-mode",
    label: "压缩提示词",
    description: "历史压缩时使用的内联覆盖内容。",
    defaultBehavior: "未设置时使用 Codex 默认的历史压缩提示词。",
    recommendedScope: "either",
    kind: "string",
  },
] as const;

export { sectionRegistry };