import { defaultFieldValues } from "./defaults";
import { sectionRegistry } from "./sections";
import type { ConfigFieldDefinition } from "../types";

export const fieldRegistry: readonly ConfigFieldDefinition[] = [
  {
    keyPath: "model",
    sectionId: "core-model",
    label: "主模型",
    description: "Codex 默认使用的主模型，通常建议保留为全局设置。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["gpt-5.4", "gpt-5.4-mini", "gpt-5.4-codex"],
    defaultValue: defaultFieldValues.model,
  },
  {
    keyPath: "service_tier",
    sectionId: "core-model",
    label: "服务档位",
    description: "控制模型调用的服务档位，影响响应速度和成本取向。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["fast", "flex"],
    defaultValue: defaultFieldValues.service_tier,
  },
  {
    keyPath: "model_reasoning_effort",
    sectionId: "reasoning-output",
    label: "推理强度",
    description: "控制模型在回答前投入的推理程度。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["minimal", "low", "medium", "high", "xhigh"],
    defaultValue: defaultFieldValues.model_reasoning_effort,
  },
  {
    keyPath: "approval_policy",
    sectionId: "security-sandbox",
    label: "审批策略",
    description: "决定何时需要人工确认命令或工具调用。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["untrusted", "on-request", "never"],
    risk: "warning",
    defaultValue: defaultFieldValues.approval_policy,
  },
  {
    keyPath: "sandbox_mode",
    sectionId: "security-sandbox",
    label: "沙箱模式",
    description: "控制文件系统与网络访问的安全边界。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["read-only", "workspace-write", "danger-full-access"],
    risk: "danger",
    defaultValue: defaultFieldValues.sandbox_mode,
  },
  {
    keyPath: "windows.sandbox",
    sectionId: "security-sandbox",
    label: "Windows 沙箱",
    description: "设置 Windows 原生沙箱模式。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["unelevated", "elevated"],
    risk: "warning",
    defaultValue: defaultFieldValues["windows.sandbox"],
  },
  {
    keyPath: "web_search",
    sectionId: "search-experience",
    label: "Web 搜索",
    description: "控制搜索结果的使用方式与刷新策略。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["disabled", "cached", "live"],
    defaultValue: defaultFieldValues.web_search,
  },
  {
    keyPath: "history.persistence",
    sectionId: "history-notifications",
    label: "历史持久化",
    description: "决定历史记录保存方式。",
    recommendedScope: "project",
    kind: "enum",
    allowedValues: ["save-all", "none"],
  },
  {
    keyPath: "history.max_bytes",
    sectionId: "history-notifications",
    label: "历史上限",
    description: "限制历史文件的最大体积。",
    recommendedScope: "project",
    kind: "number",
    risk: "warning",
  },
  {
    keyPath: "profile",
    sectionId: "profiles",
    label: "Profile",
    description: "启用的配置预设名称。",
    recommendedScope: "global",
    kind: "string",
  },
  {
    keyPath: "model_provider",
    sectionId: "model-providers",
    label: "模型提供商",
    description: "默认模型提供商标识。",
    recommendedScope: "global",
    kind: "enum",
    allowedValues: ["openai"],
  },
  {
    keyPath: "oss_provider",
    sectionId: "model-providers",
    label: "OSS 提供商",
    description: "--oss 会话使用的默认提供商。",
    recommendedScope: "global",
    kind: "string",
  },
  {
    keyPath: "project_doc_max_bytes",
    sectionId: "project-trust",
    label: "项目文档上限",
    description: "限制首轮指令中嵌入的项目文档字节数。",
    recommendedScope: "global",
    kind: "number",
  },
  {
    keyPath: "project_doc_fallback_filenames",
    sectionId: "project-trust",
    label: "项目文档兜底文件名",
    description: "当目录缺少 AGENTS.md 时使用的候补文件名列表。",
    recommendedScope: "global",
    kind: "array",
  },
  {
    keyPath: "developer_instructions",
    sectionId: "expert-mode",
    label: "开发者指令",
    description: "注入到 AGENTS.md 之前的额外指令内容。",
    recommendedScope: "either",
    kind: "string",
    risk: "warning",
  },
  {
    keyPath: "compact_prompt",
    sectionId: "expert-mode",
    label: "压缩提示词",
    description: "历史压缩时使用的内联覆盖内容。",
    recommendedScope: "either",
    kind: "string",
  },
] as const;

export { sectionRegistry };
